name: Metageno_guerrero

on:
  push:
    branches: [main]
  pull_requests:
    branches: [main]

jobs:
  metagenomics:
    runs-on: windows-latest
    container:
    image: continuumio/miniconda3

  steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Instalar Conda y el environment 
      run:

    - name: Comprobar calidad de lecturas
      run:

    - name: Recorte y filtrado
      run:

    - name: Ensamblaje del metagenoma 
      run:

    - name: Binning 
      run:

    - name: Asignacion taxonomica (Kraken) 
      run:

    - name: Visualización taxonomica 
      run:

    - name: Analisis en R 
      run:
      
    - name: Publicar artefactos
      uses: actions/upload-artifact@v3
        with:
          name: metagenomics-results
          path: output/
